name: dqt demo ci/cd

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    run-on: ubuntu-latest
    steps:
    - use: action/checkout@v2
    - name: Setup jdk 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
    - name: Build with maven
      run: mvn -B package --file pom.xml